### PR TITLE
fix: add `freebsd` flag to nonCGO build (#947)

### LINKED ISSUE #947: internal/database/database.go:59:10: undefined: OpenSQLiteDatabase
## Data
- **Shiori version**: v1.7.0 branch
- **Database Engine**: SQLite (the default).
- **Operating system**: FreeBSD 14
- **CLI/Web interface/Web Extension**: CLI

## Describe the bug / actual behavior

Trying to build Shiori from source results in:

    internal/database/database.go:59:10: undefined: OpenSQLiteDatabase

## Expected behavior
The build should succeed.

## To Reproduce
1. `git clone https://github.com/go-shiori/shiori.git`
2. `git checkout v1.7.0`
3. `go build`

## Notes
Likely not a bug; rather, I'm missing something in the build process.

### PR DESCRIPTION
**Pull request by lifepillar**
Fix broken build on FreeBSD after commit 02247b215b2fa1c1c18f651561092290ed2a5058.

FIxes #947

### CODE REVIEW

**Comment by fmartingr** [comment]
Thank you for your contribution!
